#!/usr/bin/env ruby
$LOAD_PATH.unshift(File.dirname(__FILE__))
$LOAD_PATH.unshift(File.dirname(__FILE__) + "/../../lib/ruby")
$LOAD_PATH.unshift(File.dirname(__FILE__) + "/../data")

require 'botventure'

server = Botventure::GameServer.new
server.start

require 'bots/samplebot.rb' if ARGV.length == 0
#require 'player.rb' if ARGV.length == 0
require ARGV[0] if ARGV.length == 1

player = Player.new

bot = Botventure::Robot.new
bot.connect

while bot.is_connected? && bot.is_playing? && !server.disconnected? do
  current_turn = bot.turn
  player.do_turn(bot)
  if bot.turn == current_turn then
    puts "You must take exactly one action every turn. (Use bot.wait to do nothing.)"
    break
  end
  if bot.turn > current_turn + 1 then
    puts "You must take exactly one action every turn. (You performed #{bot.turn - current_turn}.)"
    break
  end
end

if bot.is_winner? then
  puts "You win!"
else
  puts "You lose!"
end

server.stop
